project:
  type: website
  output-dir: docs

website:
  title: "Emmie Appl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Vizualization
        menu:
          - text: "Valentine's Retail"
            href: Valentines.html
          - text: "European Drug Development"
            href: UKdrugs.html
      - text: "String Analyses"
        href: StringAnalysis.html
      - text: "Slots Simulation"
        href: Slots.html
      - text: "Open Policing Project"
        href: OpenPolicing.html
      - text: "Ethics"
        href: Ethics.html

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

