project:
  type: website
  output-dir: docs

website:
  title: "Emmie Appl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
          - text: "Valentine's"
            href: Valentines.html
          - text: "European Drug Development"
            href: UKdrugs.html
      - text: "String Analyses"
        href: StringAnalysis.html
      - text: "Slots Simulation"
        href: Slots.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

