---
title: "European Drug Development"
description: |
  Analysis of European Drug Development data from TidyTuesday
author: Emmie Appl
date: February 12, 2025
format:
  html:
    code-fold: true
    code-summary: "Show the code"
execute:
  warning: false
  message: false
---

This data set includes the drugs considered for authorization in the European Union between 1995 and 2023. A generic medicine is developed to be the same as a medicine that has already been authorized, with the same active ingredient(s) and dosage(s) to treat the same condition(s). Accelerated assessment indicates that the medicine is a major interest for public health, so its time frame for review is 150 evaluation days rather than 210.

```{r fig.alt = "Bar chart comparing the number of drugs considered for authorization in the European Union between 1995 and 2023 that were generic medicines or not generic medicines. There were about 1650 non generic medicines and 300 generic medicines. In addition, the number of drugs in each category that were approved for accelerated assessment is denoted by a different color fill within the bar. No generic medicines were approved for accelerated assessment while approximately 100 generic medicines were approved for accelerated assessment."}
tuesdata <- tidytuesdayR::tt_load('2023-03-14')

drugs <- tuesdata$drugs

library(ggplot2)

ggplot(drugs, aes(y = generic)) +
  geom_bar(aes(fill = accelerated_assessment)) +
  labs(
    y = "Generic Medicine",
    x = "Drug Count",
    fill = "Accelerated Assessment"
  )
```

The majority of the drugs considered for authorization in the European Union between 1995 and 2023 were not generic medicines, meaning they were not the same as a medicine that had already been authorized. No generic medicines were selected for accelerated assessment. This is logical, as there should not be a need to speed up the review for drugs that already exist. A very small portion of non generic (new) drugs were selected for accelerated assessment, indicating that accelerated assessment is a rare occurrence.

[TidyTuesday 2023-03-14](https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-03-14/readme.md)

Data from [European Medicines Agency](https://www.ema.europa.eu/en/medicines/download-medicine-data) via [Miquel Anglada Girotto](https://github.com/MiqG/EMA-Data-Scratching-with-RSelenium)
